### ISSUE TITLE
Error seems like cookie tossing is happening. visit here: http://git.io/q4IRHQ

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Holtzmann#929]
https://sentry.io/newspring-church/newspring/issues/154820673/

```
Error: seems like cookie tossing is happening. visit here: http://git.io/q4IRHQ
  at None (/2abfcdbb8a0db13ff0ac1cba247cfd8ce14fd147.js:159:3242)
```

**Comment by johnthepink** [comment]
My gut is that this happens when we ship a new build, and the containers switch out, while people have the site open in their browser. Or, when we have shipped a new build, and someone wakes up their computer with the site open.

If that's the case, would we need to handle this at the load balancer level? Is that even possible?

**Comment by jbaxleyiii** [comment]
@johnthepink one immediate thing we should do is stop having this break the app!

**Comment by jonhorton** [comment]
I hate it when I toss my cookies
